[package]
name = "kg-service"
version = "0.1.0"
authors = ["Anthony Weston <anthonyelliotweston@gmail.com>"]

[dependencies]
mio = "0.5"
http-muncher = "0.2.0"
rustc-serialize = "0.3.15"
sha1 = "0.1.1"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"